name: Build Packages
on:
  push:
    branches: 
      - main
      - next
      - next-major
      - aplha
      - beta
      - '[0-9]+.[0-9]+.x'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
    - name: Build and publish packages
      id: build
      uses: Hexalith/Hexalith.Builds/Github/package-release@main
      with:
        project-name: ${{ github.event.repository.name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    
